name: Build Pipeline

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reservation_alert/requirements.txt

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
        with:
          # Path to your pre-commit configuration file
          config: .pre-commit-config.yaml

      - name: Run tests
        run: python -m unittest discover -s reservation_alert
